In [1]:
import numpy as np

In [2]:
def create_random_matrix(n):
  """Creates a random matrix with nxn dimensions and random numbers ranging from 0 to 255."""
  matrix = np.random.randint(0, 256, (n, n))
  return matrix

def unroll_matrix(matrix):
  """Unrolls the matrix into a vector."""
  x_ur = matrix.reshape(-1, 1)
  return x_ur

def hadamard_matrix(order):
    if order == 1:
        return np.array([[1]])
    
    if order % 2 == 1:
        raise ValueError("Order must be a power of 2.")
    
    # Generate a Hadamard matrix of half the order
    h_half = hadamard_matrix(order // 2)
    
    # Create the Hadamard matrix of the given order by combining the four quadrants
    h_top_left = h_half
    h_top_right = h_half
    h_bottom_left = h_half
    h_bottom_right = -h_half
    
    return np.block([[h_top_left, h_top_right], [h_bottom_left, h_bottom_right]])


In [3]:
n = 4
X = create_random_matrix(n)
print('X')
print(X.shape)
print(X)

X
(4, 4)
[[  4  68  59 255]
 [215  13  68 144]
 [187  48 181 195]
 [150  75  68 148]]


In [4]:
X_UR = unroll_matrix(X)
print('X unrolled')
print(X_UR.shape)
print(X_UR)

X unrolled
(16, 1)
[[  4]
 [ 68]
 [ 59]
 [255]
 [215]
 [ 13]
 [ 68]
 [144]
 [187]
 [ 48]
 [181]
 [195]
 [150]
 [ 75]
 [ 68]
 [148]]


A is selected as Hadamard matrix

- Orthogonality
- Incoherence
- Universality

In [5]:
A = hadamard_matrix(n*n)
print('A')
print(A.shape)
print(A)

A
(16, 16)
[[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1  1 -1]
 [ 1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1]
 [ 1 -1 -1  1  1 -1 -1  1  1 -1 -1  1  1 -1 -1  1]
 [ 1  1  1  1 -1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1]
 [ 1 -1  1 -1 -1  1 -1  1  1 -1  1 -1 -1  1 -1  1]
 [ 1  1 -1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1  1  1]
 [ 1 -1 -1  1 -1  1  1 -1  1 -1 -1  1 -1  1  1 -1]
 [ 1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 1 -1  1 -1  1 -1  1 -1 -1  1 -1  1 -1  1 -1  1]
 [ 1  1 -1 -1  1  1 -1 -1 -1 -1  1  1 -1 -1  1  1]
 [ 1 -1 -1  1  1 -1 -1  1 -1  1  1 -1 -1  1  1 -1]
 [ 1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1  1]
 [ 1 -1  1 -1 -1  1 -1  1 -1  1 -1  1  1 -1  1 -1]
 [ 1  1 -1 -1 -1 -1  1  1 -1 -1  1  1  1  1 -1 -1]
 [ 1 -1 -1  1 -1  1  1 -1 -1  1  1 -1  1 -1 -1  1]]


In [6]:
P = hadamard_matrix(n)
print('P')
print(P.shape)
print(P)

P
(4, 4)
[[ 1  1  1  1]
 [ 1 -1  1 -1]
 [ 1  1 -1 -1]
 [ 1 -1 -1  1]]


Traditional measurment

In [7]:
Y_from_A = np.matmul(A, X_UR)
print('Y sampled from A')
print(Y_from_A.shape)
print(Y_from_A)

Y sampled from A
(16, 1)
[[1878]
 [ -14]
 [-358]
 [ 718]
 [ 116]
 [-256]
 [-408]
 [-148]
 [-226]
 [-254]
 [ -94]
 [ 102]
 [-224]
 [-516]
 [-108]
 [-144]]


Measurement in MOSAIC

In [8]:
Y_from_P = np.matmul(P, np.matmul(X, P.T))
print('Y sampled from P')
print(Y_from_P.shape)
print(Y_from_P)

Y sampled from P
(4, 4)
[[1878  -14 -358  718]
 [ 116 -256 -408 -148]
 [-226 -254  -94  102]
 [-224 -516 -108 -144]]


Comparing the 2 measurments

In [9]:
Y_from_P_UR = unroll_matrix(Y_from_P)
print(Y_from_A == Y_from_P_UR)

[[ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]]


## Constructing A from P

In [18]:
PP = P  # 4x4

AA_2 = np.block([[PP, PP], [PP, -1*PP]]) # 8x8
AA = np.block([[AA_2, AA_2], [AA_2, -1*AA_2]]) #16x16

AA==A

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  Tru